zhmccli/_cmd_partition.py

Cherry-picked PR zhmcclient/python-zhmcclient#432 based upon its commit 28399fa.
Verified that the latest version of that PR is still consistent with what was picked.

Add CLI support for mount and unmount an ISO

---

Makefile
docs/changes.rst
remove_duplicate_setuptools.py

(#1) Fix build_clib issue on Travis by removing duplicate setuptools

---

Makefile
docs/changes.rst
remove_duplicate_setuptools.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #24.
Ready for review and merge (still into 0.18.0).

(#3) Added the zhmcclient version to the output of 'zhmc --version'

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

**Note:** This PR is on top of PR #19.

(#5) Start 0.19.0

---

.travis.yml
Makefile
appveyor.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt

**Note:** This PR is on top of PR #22.

(#7) Fixes and improvements in Makefile.

---

.travis.yml
Makefile
appveyor.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
tests/test_dummy.py
zhmccli/_helper.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #18.

(#8) Fixes #5: Added concept for function testing zhmccli

---

.travis.yml
Makefile
appveyor.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
tests/test_dummy.py
zhmccli/_helper.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #17.

(#9) Fixes #9: Improved table output for properties that are lists

---

.travis.yml
Makefile
appveyor.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
tests/test_dummy.py
zhmccli/_cmd_lpar.py
zhmccli/_helper.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #16.

(#10) Added support for force+act.profile in LPAR ops.

---

.travis.yml
docs/changes.rst
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
zhmccli/zhmccli.py

Fixes #35, #39: Multiple fixes to get tests going again

---

.gitignore
.travis.yml
docs/changes.rst
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #36.

Ignoring .pytest_cache directory for git.

---

.travis.yml
Makefile
docs/changes.rst
requirements.txt
tests/function/test_global_opts.py
tests/function/test_info.py
zhmccli/zhmccli.py

**Note:** This PR is on top of PR #36.

Dev: Changed 'make install' to install zhmccli package as editable

---

.travis.yml
Makefile
minimum-constraints.txt

Some more fixes before the release

---

.travis.yml
Makefile
docs/conf.py
minimum-constraints.txt

**Note:** This PR is on top of PR #40.

Added debug info for package version issue to Sphinx build

---

.travis.yml
Makefile
docs/conf.py
minimum-constraints.txt

**Note:** This PR is on top of PR #41.

Build changes for consistency with zhmcclient

---

.travis.yml
Makefile
appveyor.yml
docs/conf.py
minimum-constraints.txt

**Note:** This PR is on top of PR #42.

Fixed Git rebase in Appveyor CI

---

docs/cli.rst

Docs: Fixed info about syslog destination.

---

.travis.yml
tests/function/test_info.py
tests/function/utils.py
zhmccli/zhmccli.py

These are the fixes:
* Fixed pytest-cov issue with python-coveralls downgrading coverage
* Adjusted test case in test_info.py to accomodate click 7.0
* Fixed flake8 issue on Py3 in zhmccli.py

Fixed multiple issues due to upgraded packages

---

docs/changes.rst
zhmccli/_helper.py

Made check for using readline vs pyreadline consistent

---

README.rst
docs/appendix.rst
docs/changes.rst
docs/cli.rst
docs/development.rst
docs/index.rst
docs/intro.rst
setup.py
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
zhmccli/__init__.py
zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_info.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_session.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py
zhmccli/zhmccli.py

Updated Copyright to 2019

---

docs/changes.rst

Started 0.20.0 release.

---

zhmccli/_cmd_lpar.py

Following commands were added:
- zhmc lpar stop
- zhmc lpar psw-restart
- zhmc lpar scsi-load
- zhmc lpar scsi-dump
Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>

Add more 'zhmc lpar' commands

---

.gitignore

Exclued .DS_Store from git, for MacOS

---

docs/changes.rst

Updated change log with all past items up to here

---

docs/changes.rst
docs/cli.rst
zhmccli/_cmd_metrics.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Added usage options to partition list command

---

Makefile
base-requirements.txt
dev-requirements.txt
minimum-constraints.txt
requirements.txt
setup.py

Fixed py34 install issue on Windows

---

minimum-constraints.txt

Fixed issue with new pip on coveralls link dependency

---

.pylintrc
Makefile
dev-requirements.txt
minimum-constraints.txt
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
zhmccli/__init__.py
zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_info.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_session.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py
zhmccli/zhmccli.py

Fixed Pylint issues and enforced no issues

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt

Fixed exception by pinning prompt-toolkit; Upgrade strategy eager

---

zhmccli/_helper.py

Internal enhancements in helper module

---

.pylintrc
docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vswitch.py

Included previously removed properties in lpar/cpc show; Enhanced .._find()

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
zhmccli/__init__.py
zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py

**Note: This PR is on top of PR #114 - review only the delta.**
List of commands that have been added:
New command group and commands for storage groups:
* `storagegroup create` - Create a storage group
* `storagegroup list` - List the storage groups
* `storagegroup show SG` - Show the details of a storage group
* `storagegroup delete SG` - Delete a storage group
* `storagegroup update SG` - Update properties of a storage group
* `storagegroup list_partitions SG` - List the partitions to which a storage group is attached
* `storagegroup list_ports SG` - List the candidate adapter ports of a storage group
* `storagegroup add_ports SG`- Add storage adapter ports to the candidate adapter ports of a storage group
* `storagegroup remove_ports SG` - Remove …

Added support for storage mgmt commands

---

dev-requirements.txt
docs/changes.rst

Pinned Pygments to <2.4.0 on Python 3.4

---

minimum-constraints.txt
requirements.txt

Consistent name for 'click' package

---

dev-requirements.txt
minimum-constraints.txt

Added pipdeptree and pip-check-reqs as dep mgmt tools

---

minimum-constraints.txt

Added missing packages to minimum-constraints.txt

---

.github/workflows/test.yml

Separate package list and add show package dependency tree

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed dependency to readme-renderer and Pygments on Python 3.4

---

.github/workflows/test.yml

Added Python 3.4 with latest pkg levels to tests

---

docs/changes.rst
zhmccli/_cmd_hba.py

Fixed AttributeError when listing hbas on CPCs with storage mgmt feature

---

.pylintrc

Silenced Pylint use-a-generator issue

---

docs/changes.rst
zhmccli/_cmd_storagegroup.py

Fixed a KeyError in 'storagegroup create' and 'storagegroup update' commands

---

docs/changes.rst
zhmccli/_cmd_storagevolume.py

Fixed a KeyError in 'storagevolume create'

---

zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py

Addressed technical debt on accessing options

---

zhmccli/_cmd_adapter.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_info.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_session.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py
zhmccli/zhmccli.py

Cleanup: Changed raise_click_exception() to return exc instead

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Test: Fixed GitHub Actions test workflow failure with cmarkgfm on Windows

---

dev-requirements.txt
minimum-constraints.txt

Fixed flake8 install issue on py34

---

setup.py

Added Change Log to links shown by Pypi

---

docs/changes.rst
zhmccli/_cmd_partition.py

Added support for booting partitions from storage volume

---

.github/workflows/notify.yml

Added notify workflow for posting test results to Slack

---

docs/changes.rst
zhmccli/_cmd_cpc.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Added --all to 'cpc/lpar/partition show' and hid more props by default

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased minimum version of zhmcclient to 0.29.0

---

README.rst
dev-requirements.txt
docs/appendix.rst
docs/changes.rst
docs/conf.py
docs/index.rst
minimum-constraints.txt

Formal docs improvements

---

docs/cli.rst
zhmccli/zhmccli.py

Docs: Fixed cli section and main help text

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Release 0.20.0

---

docs/changes.rst
zhmccli/_version.py

Start 0.21.0

---

minimum-constraints.txt
requirements.txt

For the original issue, see test run https://github.com/zhmcclient/zhmccli/runs/2262991175?check_suite_focus=true

FIxed install issues on py27,34,35

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased minimum version of zhmcclient to 0.30.0

---

README.rst
setup.py

Updated doc links to latest in README and stable on Pypi

---

docs/changes.rst
zhmccli/_cmd_lpar.py

Added options for lpar scsi commands

---

docs/changes.rst
docs/cli.rst
zhmccli/__init__.py
zhmccli/_cmd_capacitygroup.py

Added support for DPM capacity groups

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Release 0.21.0

---

docs/changes.rst
zhmccli/_version.py

Start 0.22.0

---

docs/changes.rst
zhmccli/_version.py

Start 0.21.1

---

.pylintrc
docs/changes.rst
tests/function/utils.py
zhmccli/_cmd_partition.py

Fixed Pylint issues with latest pylint on py39

---

.pylintrc
docs/changes.rst
tests/function/utils.py
zhmccli/_cmd_partition.py

Rolls back PR #174 into 0.21.1

0.21: Fixed Pylint issues with latest pylint on py39

---

docs/changes.rst
zhmccli/_version.py

Release 0.21.1

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased the minimum version of zhmcclient to 0.31.0

---

docs/changes.rst
zhmccli/_version.py

Start 0.21.2

---

docs/changes.rst
zhmccli/_cmd_cpc.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Fixed earlier attempt to accomodate immutable properties

---

docs/changes.rst
zhmccli/_version.py

Release 0.21.2

---

docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_info.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py

Fixed the issue that some commands stopped the spinner too early

---

docs/changes.rst
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_storagegroup.py
zhmccli/_helper.py

Added a '-T' / '--operation-timeout' option to commands using async HMC ops

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py

LPAR/Partition commands using list permitted and removed need for CPC access

---

README.rst
docs/cli.rst
docs/intro.rst

Docs: Made variables are HMC user more consistent

---

docs/changes.rst
zhmccli/_cmd_nic.py

Fixed and improved options for backing port/vswitch on 'nic create/update'

---

minimum-constraints.txt
requirements.txt

Upgraded minimum zhmcclient version to 0.32.0

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Release 0.22.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.0.0

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased zhmcclient to 1.0.0

---

docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_storagevolume.py
zhmccli/_helper.py

Fixed and improved help text and defaults of command options

---

docs/changes.rst
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py

Added support for secure-boot

---

docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py

The change has been tested manually against the M96 HMC in BOE.

Fixed HTTP errors raised as traceback during various 'list' commands

---

docs/changes.rst
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py

Tested manually on ASH AZ3 with:
* `nic update ... --vlan-id ''`
* `partition update ... --ssc-ipv4-gateway ''`

Added setting props of lpar, partition, nic to null; Clarified mult. DNS servers

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Please approve the release of zhmccli version 1.0.0.

Release 1.0.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.1.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.0.1

---

docs/changes.rst
setup.py

Changed development status on Pypi to Production/Stable

---

docs/changes.rst
zhmccli/_version.py

Release 1.0.1

---

docs/changes.rst
zhmccli/_version.py

Start 1.0.2

---

.pylintrc
dev-requirements.txt
docs/changes.rst
docs/conf.py
minimum-constraints.txt
setup.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Fixed new issues reported by Pylint 2.10

---

.pylintrc
dev-requirements.txt
docs/changes.rst
docs/conf.py
minimum-constraints.txt
setup.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Rolls back PR #228 into 1.0.2.

1.0: Fixed new issues reported by Pylint 2.10

---

.pylintrc
docs/changes.rst
zhmccli/_helper.py

Ignored Pylint issue 'consider-using-f-string' in new Pylint 2.11

---

docs/changes.rst
zhmccli/_helper.py

Improved error handling of zhmcclient exceptions

---

docs/changes.rst
zhmccli/_helper.py

Rolls back PR #238 into 1.0.2.

1.0: Improved error handling of zhmcclient exceptions

---

dev-requirements.txt
minimum-constraints.txt

Fixed incompatibility between Sphinx and docutils on py27

---

zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py

Consolidated object names in messages

---

docs/changes.rst
zhmccli/_helper.py

Fixed confusing CR in Aborting message when breaking prompts

---

docs/changes.rst
docs/cli.rst
zhmccli/__init__.py
zhmccli/_cmd_character_rule.py
zhmccli/_cmd_password_rule.py
zhmccli/_cmd_user.py
zhmccli/_cmd_user_role.py
zhmccli/_helper.py

See the commit message for details.
There are several TODOs in the code, that I would like to leave for future work.

Added support for user-related command groups

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
zhmccli/_cmd_cpc.py
zhmccli/_helper.py

Ready for test and review.
The two new commands are:
```
zhmc cpc dpm-export
zhmc cpc dpm-import
```

Added support for DPM config export/import

---

.github/workflows/test.yml
Makefile
base-requirements.txt
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
setup.py
tox.ini
zhmccli/_helper.py

For details, see commit messages.

Added support for Python 3.10; Improved version consistency; Removed (py)readline

---

zhmccli/_cmd_password_rule.py
zhmccli/_cmd_user.py
zhmccli/_cmd_user_role.py

Fixed options in user/pwrule create; Added defaults to user/pwrule/userrole help

---

docs/changes.rst
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py

Fixed part dump with timeout opt; Fixed sg delete with email opts

---

Makefile
docs/changes.rst

Rolls back that part of PR #251 into 1.0.3

1.0: Removed building of the Windows binary install program

---

docs/changes.rst
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py

Rolls back PR #255 into 1.0.3.

1.0: Fixed part dump with timeout opt; Fixed sg delete with email opts

---

Makefile
docs/changes.rst

ChangeLog: Added 'Removed building of the Windows binary install program'

---

docs/changes.rst
zhmccli/_version.py

Start 1.0.4

---

docs/changes.rst
zhmccli/_cmd_user.py

See commit message for details.

Added an option '--like' to 'user create'; Fixed the setting of 'mfa-types'

---

README.rst
docs/intro.rst

Changed Quickstart example to take less time

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Please approve the release of zhmccli 1.1.0.
Change log: https://github.com/zhmcclient/zhmccli/blob/release_1.1.0/docs/changes.rst

Release 1.1.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.2.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.1.1

---

docs/changes.rst
zhmccli/_version.py

No review needed, only two bug fixes.

Release 1.1.1

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased zhmcclient to 1.2.1 (scsi-dump fix)

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Please approve the release of zhmccli 1.2.0.

Release 1.2.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.3.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.2.1

---

tests/function/test_info.py

1.2: Adjusted testcases to new error format of zhmcclient 1.3.3

---

docs/changes.rst
zhmccli/_cmd_nic.py

Tested manually on M12 and T224.

Fixed issues with --vlan-id on nic create/update

---

docs/changes.rst
zhmccli/_cmd_nic.py

1.2: Fixed issues with --vlan-id on nic create/update

---

docs/changes.rst
zhmccli/_version.py

Release 1.2.1

---

docs/changes.rst
zhmccli/_version.py

Start 1.2.2

---

docs/changes.rst
zhmccli/_helper.py
zhmccli/zhmccli.py

Help messages utilize terminal width

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed a flake8 AttributeError by pinning importlib-metadata

---

zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

Defined and used constants for API versions of new HMC versions

---

docs/changes.rst
zhmccli/_cmd_user.py

Rolls back PR #303 into 1.2.2.

1.2: Fixed user create error with mfa-types on HMC 2.14 or older

---

docs/changes.rst
zhmccli/_version.py

Start 1.2.3

---

zhmccli/_cmd_partition.py

Fixed incorrect detection of --boot-iso option in partition update

---

docs/changes.rst
zhmccli/_cmd_cpc.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py

Added/extended --acceptable-status option

---

docs/changes.rst
zhmccli/_version.py

Release 1.2.3

---

docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_password_rule.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_user.py
zhmccli/_cmd_user_role.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py

For details, see the commit message
No review needed
Tested manually on M12, S303, T224

Added artificial name props for uri props; fixes

---

.github/workflows/test.yml
docs/changes.rst
zhmccli/_version.py

Release 1.3.0

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
zhmccli/_cmd_adapter.py

Added a new command 'zhmc adapter list-nics'

---

.github/workflows/test.yml
docs/changes.rst

Fixed install of Python 2.7-3.6 on ubuntu

---

.github/workflows/test.yml
docs/changes.rst

Rolls back PR #327 into 1.4.1.

1.4: Fixed install of Python 2.7-3.6 on ubuntu

---

.github/workflows/publish.yml
.github/workflows/test.yml
docs/changes.rst
docs/development.rst

Simplified release process by pushing a tag

---

docs/development.rst

Docs: Fixed incorrect links in development section

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Upgrade zhmcclient to 1.6.0 release

---

.github/workflows/test.yml
docs/changes.rst

Added more test environments to full and normal tests

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Added tox and virtualenv to dependencies

---

dev-requirements.txt
minimum-constraints.txt

Fixed missing dependencies reported by check_reqs

---

.safety-policy.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Increased minimum versions of pip, setuptools, wheel to more recent

---

.github/workflows/test.yml
Makefile
dev-requirements.txt
minimum-constraints.txt
requirements.txt

Added safety to Makefile and Actions test workflow, ignoring issues

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt

Addressed issues reported by safety

---

Makefile

Fixed pip install on Windows to use python -m pip install

---

.travis.yml

Added pip list to Travis steps

---

docs/changes.rst
zhmccli/_cmd_cpc.py

1.5: Fixes #362: adapter mapping file schema

---

docs/changes.rst
tests/function/test_cpc_dpmexport_opts.py
tests/function/test_cpc_dpmimport_opts.py
zhmccli/_cmd_cpc.py

Fixed TypeError with cpc dpm-export/import commands and Click 8

---

minimum-constraints.txt
requirements.txt
setup.py

Fixed zhmcclient dependency issue in local 'make install'

---

minimum-constraints.txt
requirements.txt
setup.py

Rolls back PR #375 into 1.5.1.

1.5: Fixed zhmcclient dependency issue in local 'make install'

---

.gitignore

1.5: Ignored MANIFEST files for git

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

1.5: Increased zhmcclient to 1.7.0

---

docs/changes.rst
zhmccli/_version.py

Please approve the release of zhmccli 1.5.1 to Pypi.
Main review point: Do we expect more bug fixes that should be included?

Release 1.5.1

---

docs/changes.rst
zhmccli/_version.py

Start 1.5.2

---

.github/workflows/test.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
setup.py
tox.ini

Added support for Python 3.11

---

docs/changes.rst
zhmccli/_cmd_cpc.py

* Add new flag --include-unused-adapters for dpm export
* Fixed a few typos

Fixes #369: add support for --include-unused-adapters

---

docs/development.rst

No review needed - the same change was reviewed as part of PR https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/304

Improved dev docs on releasing/starting a version

---

.whitesource

Enabled whitesource Mend checking

---

SECURITY.md

Added security policy; enabled private viulnerability reporting

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints.txt

Rolls back PR #394 into 1.6.1.

1.6: Fixed coveralls issues with KeyError and HTTP 422 Unprocessable Entity

---

docs/changes.rst
tests/function/test_info.py

Test: Fixed test_info.py test that broke with new urllib3 version 2.0.2

---

docs/changes.rst
tests/function/test_info.py

Rolls back PR #400 into 1.6.1.

1.6: Test: Fixed test_info.py test that broke with new urllib3 version 2.0.2

---

Makefile

Used PACKAGE_LEVEL in file name of .done files

---

.readthedocs.yaml
docs/changes.rst

Rolls back PR #397 into 1.6.1.

1.6: Fixed RTD docs build issue with OpenSSL

---

.readthedocs.yaml
docs/changes.rst

Fixed RTD docs build issue with OpenSSL

---

docs/changes.rst
zhmccli/_version.py

Start 1.7.0 (after the facts)

---

docs/changes.rst
zhmccli/_helper.py

Rolls back PR #391 into 1.6.1.

1.6: Fixed incorrect representation of string values as floating point numbers

---

docs/changes.rst
zhmccli/_helper.py
zhmccli/zhmccli.py

Added a hidden '--pdb' general option

---

docs/changes.rst
zhmccli/__init__.py
zhmccli/_cmd_ldap_server_definition.py

Added support for LDAP Server Definitions

---

docs/changes.rst
zhmccli/__init__.py
zhmccli/_cmd_certificates.py
zhmccli/_cmd_console.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

No review needed - was reviewed in internal repo

Merge changes for z16 GA1.5

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/end2end/test_session.py
zhmccli/zhmccli.py

Increased zhmcclient to 1.8.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.8.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.7.1

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/end2end/test_session.py
tests/end2end/utils.py
zhmccli/_cmd_session.py
zhmccli/_helper.py

Fixed automatic logoff of sessions; Improved session end2end tests

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/end2end/test_session.py
tests/end2end/utils.py
zhmccli/_cmd_session.py
zhmccli/_helper.py

Rolls back PR #422 into 1.7.1.

1.7: Fixed automatic logoff of sessions; Improved session end2end tests

---

minimum-constraints.txt
requirements.txt

Fixed dependency on zhmcclient 1.8.1 to be from Pypi

---

.github/workflows/test.yml
docs/changes.rst

Circumvented the removal of Python 2.7 from setup-python

---

.github/workflows/test.yml
docs/changes.rst

1.7: Circumvented the removal of Python 2.7 from setup-python

---

.safety-policy.yml
docs/changes.rst
minimum-constraints.txt

Rolls back PR #430 into 1.7.1.

1.7: Addressed safety issues from 6/2023

---

.safety-policy.yml
docs/changes.rst
minimum-constraints.txt

Addressed safety issues from 6/2023

---

docs/changes.rst
zhmccli/_version.py

Release 1.7.1

---

docs/changes.rst
zhmccli/_version.py

Start 1.7.2

---

zhmccli/_cmd_console.py

Added missing spinner stop to console restart command

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Increased zhmcclient to 1.8.2

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

1.7: Fixed safety issues 7/2023

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt

Fixed PyYAML dependency to to release of Cython 3

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt

Rolls back PR #442 into 1.7.2.

1.7: Fixed PyYAML dependency to to release of Cython 3

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt

Used zhmcclient 1.10.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.9.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.8.1

---

dev-requirements.txt
minimum-constraints.txt

Addresses dependabot issues from 9/7

---

Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Upgraded minimum versions

---

.safety-policy.yml

Fixed safety issues from 2023-09-26

---

.safety-policy.yml

Rolls back PR #462 into 1.8.1.

1.8: Fixed safety issues from 2023-09-26

---

.safety-policy.yml
dev-requirements.txt
minimum-constraints.txt

Fixed safety issues from 10/3

---

.safety-policy.yml
dev-requirements.txt
minimum-constraints.txt

Rolls back PR #469 into 1.8.1.

1.8: Fixed safety issues from 10/3

---

docs/changes.rst
zhmccli/_cmd_adapter.py
zhmccli/_cmd_capacitygroup.py
zhmccli/_cmd_certificates.py
zhmccli/_cmd_character_rule.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_ldap_server_definition.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_storagegroup.py
zhmccli/_cmd_storagevolume.py
zhmccli/_cmd_user.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vstorageresource.py
zhmccli/_cmd_vswitch.py

Added columns to the output of list commands

---

docs/changes.rst
zhmccli/_cmd_partition.py

Added missing partition create/update properties

---

zhmccli/_cmd_ldap_server_definition.py

No review needed. Fixes PR #476

Fixed ldapdef/ldapsd parameter in ldap functions

---

.github/workflows/test.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
setup.py
tox.ini

Added support for Python 3.12

---

docs/changes.rst
minimum-constraints.txt
requirements.txt
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_user.py

To see the option grouping, use e.g. `zhmc partition create --help`

Grouped options in help of partition/lpar/user create/update commands

---

zhmccli/_cmd_partition.py

As a result partition create is currently broken throwing e.g.,` KeyError: 'ifl-absolute-capping'`.

Restore options lost with PR #492

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Addressed safety issues up to 2023-11-05

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Use zhmcclient 1.12.0 as a minimum

---

.safety-policy.yml
minimum-constraints.txt
requirements.txt

Rolls back PR #521 into 1.9.2.

1.9: Safety issues from 2023-11-20

---

zhmccli/_cmd_partition.py

No review needed, fixes only a comment.

Fixed comment on partition update --boot-configuration

---

.safety-policy.yml
docs/changes.rst
minimum-constraints.txt

Rolls back PR #529 into 1.9.2.

1.9: Addressed safety issues up to 2023-11-26

---

docs/changes.rst
zhmccli/_cmd_lpar.py

lpar update: Added most of the missing options; fixed zAware/SSC master pw

---

docs/changes.rst
zhmccli/_version.py

Start 1.9.3

---

Makefile
docs/changes.rst
tests/unit/test_helper.py
zhmccli/_cmd_imageprofile.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_resetprofile.py
zhmccli/_helper.py

This PR implements option 3 described in issue #515.

Support for remaining complex-valued options on lpar,imageprofile,resetprofile

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Safety issues 2024-01-13; prompt-toolkit version

---

.github/workflows/test.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed Sphinx / sphinxcontrib-applehelp version issue

---

.github/workflows/test.yml
docs/changes.rst

Increased versions of GitHub Actions plugins to node 20

---

docs/changes.rst
zhmccli/_cmd_lpar.py

added missing support for lpar start group command

added support for lpar start command

---

README.rst
docs/_static/basic.css
docs/_static/classic.css
docs/appendix.rst
docs/changes.rst
docs/cli.rst
docs/development.rst
docs/index.rst
docs/intro.rst
setup.py
tests/function/test_global_opts.py
tests/function/test_info.py
tests/function/utils.py
zhmccli/__init__.py
zhmccli/_cmd_adapter.py
zhmccli/_cmd_certificates.py
zhmccli/_cmd_cpc.py
zhmccli/_cmd_hba.py
zhmccli/_cmd_info.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_metrics.py
zhmccli/_cmd_nic.py
zhmccli/_cmd_partition.py
zhmccli/_cmd_port.py
zhmccli/_cmd_session.py
zhmccli/_cmd_vfunction.py
zhmccli/_cmd_vswitch.py
zhmccli/_helper.py
zhmccli/zhmccli.py

Fixed copyright statements that have year-year range to year,year

Fixed Copyright statements

---

docs/changes.rst
zhmccli/_cmd_character_rule.py

Rolls back PR #555 into 1.9.3.

1.9: Fixed KeyError in characterrule list

---

docs/changes.rst
zhmccli/_cmd_user.py

Fixed user create --like for non-LDAP or non-MFA users

---

Makefile
docs/changes.rst
minimum-constraints.txt
requirements.txt

Using released version of zhmcclient 1.13.4

---

tests/unit/test_helper.py
zhmccli/_cmd_cpc.py
zhmccli/_helper.py

Particular review points:
* Change of format for --ec-levels options

Fixes and format change for --ec-levels option in firmware commands

---

docs/changes.rst
tests/unit/test_helper.py
zhmccli/_cmd_adapter.py
zhmccli/_cmd_partition.py
zhmccli/_helper.py

New commands:
* `zhmc adapter show-crypto`
* `zhmc partition show-crypto`
* `zhmc partition add-crypto`
* `zhmc partition remove-crypto`
* `zhmc partition zeroize-crypto`
Tested all new commands manually on A224.

Added crypto related commands

---

.github/workflows/test.yml
docs/changes.rst

Fixed call to pipdeptree in test workflow

---

.safety-policy-install.yml

Optimized safety ignore list for install

---

docs/changes.rst
zhmccli/_version.py

Release 1.9.3

---

docs/changes.rst
zhmccli/_version.py

Release 1.10.0

---

docs/changes.rst
zhmccli/_version.py

Start 1.10.1

---

docs/changes.rst
zhmccli/_version.py

Start 1.11.0

---

AUTHORS.md

1.10: Added missing AUTHORS.md file

---

AUTHORS.md

Added missing AUTHORS.md file

---

.safety-policy-all.yml
.safety-policy-install.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed issue with ignoring unpinned reqs with safety 3.0 and made that minimum

---

.safety-policy-all.yml
minimum-constraints.txt

Safety issues for all, up to 2024-02-18

---

.safety-policy-install.yml
Makefile
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt

Improved safety run for install to use exact minimum versions

---

.github/workflows/test.yml
Makefile
docs/changes.rst
docs/development.rst
minimum-constraints-install.txt
minimum-constraints.txt

Safety run for all dependencies now must succeed when releasing

---

base-requirements.txt
dev-requirements.txt
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt

Clarified comments in constraints/requirements files

---

.safety-policy-all.yml
.safety-policy-install.yml

Clarified comments and reduced ignore rules in safety policy files

---

minimum-constraints.txt

Rolls back PR #593 into 1.10.1.

1.10: Fixed missing deps of typer package

---

docs/changes.rst
zhmccli/_cmd_cpc.py

Fix cpc-name handling for cpc autostart add

---

.safety-policy-install.yml
docs/changes.rst
minimum-constraints-install.txt
zhmccli/_cmd_metrics.py
zhmccli/_helper.py

Fixed Python 3.5 issue, safety issues, new Pylint issues

---

docs/changes.rst
tests/function/test_info.py

Fixed new issues reported by new flake8 7.0.0

---

docs/changes.rst
tests/function/test_info.py

Rolls back PR #615 into 1.11.1.

1.11: Fixed new issues reported by new flake8 7.0.0

---

docs/changes.rst
minimum-constraints-install.txt

Addressed safety issues up to 2024-06-23

---

.safety-policy-install.yml
docs/changes.rst
minimum-constraints-install.txt

Rolls back PR #621 into 1.11.1

1.11: Addressed safety issues up to 2024-06-23

---

docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt

Addressed safety issues up to 2024-07-21

---

.bandit.toml
.github/workflows/test.yml
.ruff.toml
Makefile
dev-requirements.txt
docs/changes.rst
docs/conf.py
minimum-constraints.txt
setup.py
tests/end2end/utils.py
tests/function/test_info.py
tests/unit/test_helper.py
zhmccli/_cmd_console.py
zhmccli/_cmd_cpc.py
zhmccli/zhmccli.py

Added support for ruff and bandit checkers

---

Makefile
docs/changes.rst

Dev: Changed 'make install' to install the package in non-editable mode

---

docs/changes.rst
minimum-constraints-develop.txt
minimum-constraints-install.txt

Addressed safety issues up to 2024-08-16

---

.safety-policy-all.yml
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt

Rolls back PR #636 into 1.11.1.

1.11: Addressed safety issues up to 2024-08-16

---

dev-requirements.txt
minimum-constraints-develop.txt

Added dev dependency to psutil

---

minimum-constraints.txt

Rolls back PR #638 into 1.11.1.

1.11: Added dev dependency to psutil

---

Makefile
changes/.gitignore
changes/617.feature.rst
changes/618.feature.rst
changes/619.feature.rst
changes/623.fix.rst
changes/632.feature.rst
changes/changes.rst.j2
changes/noissue.1.cleanup.rst
changes/noissue.1.incompatible.rst
changes/noissue.safety.fix.rst
dev-requirements.txt
docs/changes.rst
docs/conf.py
docs/development.rst
minimum-constraints-develop.txt
towncrier.toml

Migrated to using towncrier for managing the change log

---

Makefile
changes/noissue.2.cleanup.rst
changes/noissue.3.cleanup.rst
docs/development.rst

Dev: Relaxed the conditions when safety issues are tolerated

---

changes/noissue.4.cleanup.rst
docs/development.rst

Added release step to check and fix dependabot alerts

---

.safety-policy-install.yml
base-requirements.txt
docs/changes.rst
minimum-constraints-install.txt

Rolls back PR #646 into 1.11.1.

1.11: Addressed safety issues

---

.readthedocs.yaml
zhmccli/_version.py

Made RTD build more resilient

---

changes/noissue.1.fix.rst
docs/development.rst

Fixed step that creates the release start tag when starting a new version

---

.github/workflows/publish.yml
.github/workflows/test.yml
changes/noissue.3.fix.rst

Upgraded node.js versions in GitHub Actions workflows

---

.github/workflows/test.yml
base-requirements.txt
changes/612.feature.rst
changes/612.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt
minimum-constraints-install.txt
pyproject.toml
requirements.txt
tox.ini

Added support for and tests on Python 3.13.0-rc.1

---

Makefile
changes/645.cleanup.rst
changes/645.feature.1.rst
changes/645.feature.2.rst
dev-requirements.txt
docs/development.rst
minimum-constraints-develop.txt

Simplified release and start of a new version

---

.github/workflows/publish.yml

Fixed trigger tags in publish workflow

---

.dockerignore
Dockerfile
Makefile
changes/627.feature.rst
docs/intro.rst

No review needed, since it is the same as for the exporter.

Added support for building a local docker image

---

.github/workflows/test.yml
changes/620.feature.rst
dev-requirements.txt
minimum-constraints-develop.txt

Test: Added tests for Python 3.13 (final version)

---

Makefile
changes/662.fix.rst

Fixed incorrect check for start branch in 'make start_tag'

---

Makefile
changes/noissue.4.fix.rst

Fixed incorrect checks in 'make release_publish' and 'make start_tag'

---

Makefile
changes/noissue.5.fix.rst

Made authors creation tolerant against git shortlog not showing authors

---

Makefile
changes/noissue.5.fix.rst

Fix issue that without terminal the AUTHORS.md file was emptied

---

.mailmap
AUTHORS.md
changes/noissue.5.cleanup.rst

Consolidated the names and emails of the authors shown in AUTHORS.md

---

.github/workflows/publish.yml

Resolved packages_dir warning; added pip list

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints-develop.txt

See https://github.com/zhmcclient/python-zhmcclient/issues/1711

Fixed pydantic-core install failure

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints-develop.txt

Rolls back PR #672 into 1.12.1.

1.12: Fixed pydantic-core install failure

---

changes/noissue.safety.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

Safety issues up to 2024-11-30

---

changes/noissue.safety.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

Rolls back PR #674 into 1.12.1.

1.12: Safety issues up to 2024-11-30

---

changes/noissue.1.12.1.notshown.rst

Start 1.12.1

---

changes/noissue.2.cleanup.rst
tests/end2end/test_session.py

Cleanup and improvements as a preparation for PR #685, so that its changes are not convoluted by these cleanups and improvements. 

Improved and cleaned up end2end testcases in test_session.py

---

changes/688.feature.rst
zhmccli/zhmccli.py

For details, see the commit message or the change entries.

Improved password prompting in interactive mode

---

changes/noissue.checkreqs-dev.fix.rst
changes/noissue.safety.fix.rst
minimum-constraints-develop.txt

Fixed safety issues; Fixed missing dependencies

---

changes/noissue.checkreqs-dev.fix.rst
changes/noissue.safety.fix.rst
minimum-constraints-develop.txt

Rolls back PR #699 into 1.12.3.

1.12: Fixed safety issues; Fixed missing dependencies

---

base-requirements.txt
changes/noissue.safety.fix.rst
minimum-constraints-install.txt

1.12: Fixed safety issues

---

.github/workflows/test.yml
Makefile

Split display of env & platform; Added platform details

---

Makefile

Dev: Added missing dependency ot .py files in make install

---

tests/function/test_info.py

Eliminated use of test classes in function tests

---

tests/function/test_options.py

Eliminated use of test classes in function tests - 2

---

changes/noissue.2.fix.rst

Test: Added tests/unit/__init__.py to get coverage for unit tests

---

tests/function/test_options.py
tests/function/utils.py
tests/unit/test_csv.py
zhmccli/_helper.py
zhmccli/zhmccli.py

Added support for CSV output format

---

changes/noissue.safety.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

Increased safety to 3.4.0 and updated its dependencies; Safety issues

---

Makefile
changes/733.feature.rst
minimum-constraints-install.txt
requirements.txt
tests/end2end/test_cpc.py
tests/end2end/test_session.py
tests/end2end/utils.py

I ran the end2end tests against T224.

End2end test concept and cleanup of test support

---

Makefile
changes/690.feature.rst
minimum-constraints-install.txt
requirements.txt

Use zhmcclient 1.21.0

---

changes/753.fix.rst
zhmccli/_cmd_cpc.py
zhmccli/_cmd_imageprofile.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py

I have tested it manually with `partition create` and `partition update` on AHPS.

Fixed ignored options '--ssc-ipv4-gateway' and '--ssc-ipv6-gateway'

---

changes/753.fix.rst
zhmccli/_cmd_cpc.py
zhmccli/_cmd_imageprofile.py
zhmccli/_cmd_lpar.py
zhmccli/_cmd_partition.py

1.12: Fixed ignored options '--ssc-ipv4-gateway' and '--ssc-ipv6-gateway'

---

tests/unit/test_csv.py

Extended CSV tests to check behavior of Python csv module

---

.mailmap
AUTHORS.md

Removed the umlaut in the generated AUTHORS.md file.

Fixed Edwin's name in the authors file

---

tests/end2end/test_session.py

Adjusted end2end testcases for 'session logoff' to add creation time

---

changes/noissue.3.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

See https://github.com/snowballstem/snowball/issues/229.

Dev: Fixed Sphinx build issue by excluding snowballstemmer 3.0.0

---

changes/775.feature.rst
zhmccli/_cmd_storagevolume.py

This PR was originally created in the internal repo by Alex E. Closed it there.

Support for specifying storage volumes by UUID

---

changes/noissue.safety.fix.rst
minimum-constraints-develop.txt

Safety issues

---

.github/workflows/test.yml
changes/791.feature.rst

Added doclinkcheck to test workflow

---

Makefile
changes/797.fix.rst

Made order of names in AUTHORS.md reliable

---

changes/noissue.47.fix.rst
dev-requirements.txt

Circumvented safety issue with import of typer module

---

Makefile
changes/noissue.2.fix.rst

Fixed quoting for TESTCASES env var in Makefile

---

.bandit.toml
docs/conf.py
tests/end2end/test_session.py
tests/end2end/utils.py
tests/function/test_options.py
tests/function/utils.py
zhmccli/zhmccli.py

Moved bandit exceptions from config file to source

---

dev-requirements.txt
minimum-constraints-develop.txt

Added pydantic_core dependency
