.travis.yml, Makefile, docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmccli/_helper.py
Ready for review and merge into 0.18.0.
Changes:
* Circumvented Travis issue with build_clib.
* Fixed issue with no readline module on Windows.
* Disabled OS-X and pypy on Travis for the time being.
=> Various changes for passing Travis and Appveyor

Makefile, docs/changes.rst, remove_duplicate_setuptools.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py, zhmccli/zhmccli.py
**Note:** This PR is on top of PR #21.
Ready for review and merge (still into 0.18.0).
=> (#2) Fixed that CONSOLE_LOGGER_NAME was not migrated from zhmcclient

docs/changes.rst, minimum-constraints.txt, requirements.txt
**Note:** This PR uses the released version of zhmcclient 0.18.0, and therefore will fail until that version is released.
**Note:** When releasing zhmccli 0.18.0, the 0.18.0 tag still needs to be added once this PR is merged.
=> (#4) Release 0.18.0

.travis.yml, appveyor.yml, docs/changes.rst, minimum-constraints.txt, requirements.txt
**Note:** This PR is on top of PR #20.
Details:
- This change enables Travis and Appveyor to distinguish between quick runs and full runs. Runs from branch manual-ci-run are run as full runs (after locally rebasing to master), and all other branches are run as quick runs.
=> (#6) Enabled Travis and Appveyor for manual-ci-run.

requirements.txt
Zhmccli depends on the functionality introduced in zhmcclient with PR zhmcclient/python-zhmcclient#461. Its branch was deleted when it was merged, causing zhmccli to fail. This change pulls in the master branch of zhmcclient, until zhmcclient 0.19.0 will be released.
=> Update requirements.txt to fix zhmcclient branch

docs/changes.rst, zhmccli/_cmd_cpc.py
Added CLI support for the following CPC energy management
operations:
- set power save: zhmc cpc set-power-save
- set power capping: zhmc cpc set-power-capping
- get energy management data: zhmc cpc get-em-data
Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>
=> Add support for CPC energy management operations

docs/changes.rst
Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>
=> Updated change log for 0.19.0 release.

docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmccli/_cmd_partition.py, zhmccli/_helper.py
See the commit message for details.
This PR requires the latest master version of the zhmcclient project to be installed (e.g. `pip install .` or `pip install -e .`)
Ready for review and trying it out. To display help: `zhmc partition dump --help`
TODO:
- Pull in zhmcclient 0.29.0 once released.
=> Added 'dump' command for partitions

Makefile, dev-requirements.txt, minimum-constraints.txt
=> Circumvented an install failure of lazy-object-proxy on py35/minimum

docs/changes.rst, requirements.txt
=> Fixed install error on py>=3.6 due to click-repl incompatible with click 8.0

docs/changes.rst, requirements.txt
Rolls back PR #172 into 0.21.1
=> 0.21: Fixed install error on py>=3.6 due to click-repl incompatible with click 8.0

docs/appendix.rst, docs/changes.rst, docs/cli.rst, minimum-constraints.txt, requirements.txt, zhmccli/_cmd_session.py, zhmccli/_helper.py, zhmccli/zhmccli.py
Will require zhmcclient 0.31, currently from its master branch.
=> Added support for validating HMC server certificates

docs/changes.rst, requirements.txt
Set to priority because a release with that fix should be made very quickly.
=> 0.21: Pinned zhmcclient version to <0.31

zhmccli/_helper.py
=> Fixed missing timestats in Contextobj.repr()

zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py
No rollback into 0.21 because the problem only occurs with zhmcclient 0.31 and higher.
=> Fixed handling of immutable properties in partition list with usage options

.pylintrc, docs/changes.rst, zhmccli/_helper.py
Rolls back PR #230 into 1.0.2.
=> 1.0: Ignored Pylint issue 'consider-using-f-string' in new Pylint 2.11

zhmccli/zhmccli.py
If `is_flag` is set to `True` Click defaults to `False`. Therefore the check
if no_verify is None:
no_verify = ctx.obj.no_verify
will always fail. Fix this by setting the default to None for the click option
and apply the actual default later.
Signed-off-by: Marc Hartmayer <mhartmay@linux.ibm.com>
=> zhmccli: fix `no_verify` for nested context

minimum-constraints.txt
=> Fixed >= constraint in minimum-constraints.txt for Pygments

Makefile
=> Support for TESTOPTS containing blanks

docs/changes.rst, zhmccli/_cmd_lpar.py
=> Fixed type of --disk-partition-id option in "lpar scsi-load/scsi-dump"

docs/changes.rst, zhmccli/_cmd_lpar.py
Rolls back PR #271 into 1.1.1.
=> 1.1: Fixed type of --disk-partition-id option in "lpar scsi-load/scsi-dump"

docs/changes.rst, zhmccli/_cmd_lpar.py
I tested manually that "lpar list --names-only" now shows the CPC names.
I double checked that the same error does not also exist for "partition list --names-only".
=> Fixed that "lpar list --names-only" had an empty "cpc" column

docs/changes.rst, zhmccli/_cmd_lpar.py
Rolls back PR #273 into 1.1.1.
=> 1.1: Fixed that "lpar list --names-only" had an empty "cpc" column

docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmccli/__init__.py, zhmccli/_cmd_console.py
New commands:
* `zhmc console show`
* `zhmc console get-audit-log`
* `zhmc console get-security-log`
=> Added support for 'console' command group and retrieving audit/security logs

tests/function/test_info.py
No review needed. Testes with both zhmcclient 1.3.2 and 1.3.3.
=> Adjusted testcases to new error format of zhmcclient 1.3.3

dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #299 into 1.2.2.
=> 1.2: Fixed a flake8 AttributeError by pinning importlib-metadata

zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py, zhmccli/_helper.py
Rolls back PR #301 into 1.2.2.
=> 1.2: Defined and used constants for API versions of new HMC versions

docs/changes.rst, zhmccli/_cmd_user.py
No review required.
Tested manually.
=> Fixed user create error with mfa-types on HMC 2.14 or older

docs/changes.rst, zhmccli/_cmd_partition.py
=> Fixed --boot-iso option of 'partition update' command

docs/changes.rst, zhmccli/_cmd_partition.py
Rolls back PR #305 into 1.2.2.
=> 1.2: Fixed --boot-iso option of 'partition update' command

docs/changes.rst, zhmccli/_cmd_partition.py
Rolls back PR #311 into 1.2.3.
=> 1.2: Fixed incorrect detection of --boot-iso option in partition update

docs/changes.rst, docs/intro.rst
No review needed, since it is the same text as in PR https://github.com/zhmcclient/python-zhmcclient/pull/1093.
=> Docs: Added a section 'Setting up firewalls or proxies'

zhmccli/_cmd_cpc.py
If the API call returns with a 200 code, additional details are included in the response.
This is an example how the output will look like in this case:
```
Partially imported DPM configuration from DPM config file ./export.yaml into CPC '1X091404'. The following parts were not restored:
+---------------------+------------+
| category            | items      |
|---------------------+------------|
| boot-password-reset | partition2 |
|                     | partition1 |
+---------------------+------------+
```
Fixes #342
=> Show output of cpc dpm-import command

docs/changes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #344 into 1.4.1.
=> 1.4: Unpinned Click from <8 for py>=3.6

minimum-constraints.txt
=> Fixed tomli dependency for Python 3.6

docs/changes.rst, zhmccli/_cmd_cpc.py
- change JSON schema for mapping validation to follow WSAPI names
- update dpm-import help text accordingly
=> Fixes #362: adapter mapping file schema

docs/changes.rst, tests/function/test_cpc_dpmexport_opts.py, tests/function/test_cpc_dpmimport_opts.py, zhmccli/_cmd_cpc.py
Rolls back PR #371 into 1.5.1.
=> 1.5: Fixed TypeError with cpc dpm-export/import commands and Click 8

docs/changes.rst, zhmccli/__init__.py, zhmccli/_cmd_unmanaged_cpc.py
The main review point I think would be how the unmanaged CPCs are surfaced by the cli:
This PR introduces a new command group with a single command:
```
zhmc unmanaged_cpc list
```
The original proposal in issue #98 was to add the list command to the console command group:
```
zhmc console list-unmanaged-cpcs
```
=> Support for unmanaged CPCs

docs/changes.rst, zhmccli/_cmd_adapter.py
Note, this requires zhmcclient PR https://github.com/zhmcclient/python-zhmcclient/pull/1177, which is targeted for zhmcclient 1.8.0.
=> Support for changing crypto type and FICON type of adapters; Removed --crypto-number

.coveragerc.end2end, .gitignore, Makefile, docs/changes.rst, docs/development.rst, tests/end2end/test_session.py, tests/end2end/utils.py
Note: This PR was originally on top of PR #412 (review only the delta), but has now been rebased to master after merging that PR.
Tested the initial end2end testcase successfully against the A224 HMC (with Python 2.7 and 3.9 on macOS)
The end2end tests do not run against a mocked environment yet - created issue #413 to fix that.
=> Added initial support for end2end tests

docs/changes.rst, zhmccli/_version.py
Please approve the release of zhmccli version 1.7.0 to Pypi
=> Release 1.7.0

minimum-constraints.txt, requirements.txt
Rolls back PR #428 into 1.7.1.
=> 1.7: Fixed dependency on zhmcclient 1.8.1 to be from Pypi

dev-requirements.txt, docs/changes.rst
=> 1.8: Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

.github/workflows/test.yml
Rolls back PR #464 into 1.8.1.
=> 1.8: Moved 'make safety' to the end of the test workflow

docs/changes.rst, zhmccli/_cmd_adapter.py
=> Removed 'adapter-family' from 'adapter list' output

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #477 into 1.8.1.
=> 1.8: Bump gitpython from 3.1.35 to 3.1.37

zhmccli/_cmd_ldap_server_definition.py
Rolls back PR #476 into 1.8.1.
=> 1.8: "zhmc ldap delete": fails with TypeError #460

docs/changes.rst, zhmccli/_cmd_console.py, zhmccli/_cmd_cpc.py
=> Fixed missing 'CPC' arg in 'zhmc cpc upgrade' command

docs/changes.rst, zhmccli/_cmd_console.py, zhmccli/_cmd_cpc.py
Rolls back PR #488 into 1.9.1.
=> 1.9: Fixed missing 'CPC' arg in 'zhmc cpc upgrade' command

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #503 into 1.9.2.
=> 1.9: Resolved dependency conflict with importlib-metadata on Python 3.7

dev-requirements.txt, minimum-constraints.txt
Rolls back PR #507 into 1.9.2.
=> 1.9: Fixed ruamel.yaml issue on Python 3.6 by pinning to <0.17.22

zhmccli/_cmd_partition.py
Otherwise the create fails with a KeyError.
=> Add boot-media-type option to partition create.

.safety-policy.yml, docs/changes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #511 into 1.9.2.
=> 1.9: Addressed safety issues up to 2023-11-05

zhmccli/_cmd_adapter.py, zhmccli/_cmd_capacitygroup.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_port.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vswitch.py
Internal code consolidation. See discussion in PR #499.
=> Removed unused ability to have Cpc object in find_...() functions

docs/changes.rst, zhmccli/_cmd_lpar.py
=> Fixed that lpar ''--defined-capacity' option takes boolean argument

.safety-policy.yml, docs/changes.rst, minimum-constraints.txt, requirements.txt
=> 1.9: Safety issues 2024-01-13; prompt-toolkit version

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/changes.rst, minimum-constraints.txt
Rolls back PR #547 into 1.9.3.
=> 1.9: Fixed Sphinx / sphinxcontrib-applehelp version issue

docs/changes.rst, zhmccli/_cmd_user.py
Rolls back PR #557 into 1.9.3.
=> 1.9: Fixed user create --like for non-LDAP or non-MFA users

docs/changes.rst, zhmccli/__init__.py, zhmccli/_cmd_user_pattern.py
Manually tested on HMC 9.114.87.7 (A224 HMC)
Particular review points:
* Are the three identification methods for the user template correct? See the help for the create and update commands.
=> Added support for user patterns with a new 'zhmc userpattern' command group

Makefile, docs/changes.rst, minimum-constraints.txt, requirements.txt, zhmccli/_cmd_cpc.py, zhmccli/_helper.py
Particular review points:
* Do the options to select firmware updates in the new "zhmc cpc install-firmware" command make sense
* Name of the new commands  "zhmc cpc install-firmware" and "zhmc cpc delete-uninstalled-firmware", particularly compared to "zhmc cpc upgrade"
=> Support for installation/deletion of single firmware updates on the SE 

docs/changes.rst, zhmccli/_cmd_console.py, zhmccli/_cmd_cpc.py, zhmccli/_helper.py
Particular review points:
* Description of the installation states (retrieved, ...) in the help text
* Representation of MCL levels 000 and 0 as '-', meaning there is no such level
=> Added support for listing firmware levels of SE/CPC and HMC

.github/workflows/test.yml, docs/changes.rst
Rolls back PR #573 into 1.9.3.
=> 1.9: Fixed call to pipdeptree in test workflow

docs/changes.rst, zhmccli/_cmd_lpar.py, zhmccli/_cmd_partition.py
Tested the following manually, on both the A224 HMC (3 CPCs in DPM mode) and on the T28 HMC (4 CPCs in classic mode):
* `zhmc partition list --names-only`  
* `zhmc partition list --names-only`    # with use of list_permitted_partitions() disabled
* `zhmc partition list A224 --names-only`
* `zhmc partition list XXX --names-only`
* `zhmc lpar list --names-only`    
* `zhmc lpar list --names-only`    # with use of list_permitted_lpars() disabled
* `zhmc lpar list T28 --names-only`
* `zhmc lpar list XXX --names-only`
=>  Check in partition/lpar list that specified CPC exists 

dev-requirements.txt, minimum-constraints.txt
=> Fixed check_reqs SyntaxWarning on tox by increasing tox to 3.1.0

.safety-policy-all.yml, .safety-policy-install.yml
=> Reduced ignore rules in safety policy files

.github/workflows/test.yml, docs/changes.rst
Rolls back PR #599 into 1.10.1.
=> 1.10: Fixed macos version used in test workflow for py36/37

docs/changes.rst, zhmccli/_helper.py
This improves performance in cases where pull_full_properties contains properties that are expensive to query but are not needed in the table.
Reduces time to list CPCs from over 20 seconds to under 1 second on my test system.
=> Avoid pull_full_properties() in print_resources_as_table

docs/changes.rst, zhmccli/_cmd_partition.py
This improves performance for newer HMCs with many partitions. For my test system it reduces the time from about 20 seconds to below 3 seconds.
=> Exploit additional_properties for list partitions

docs/changes.rst, zhmccli/_cmd_cpc.py
Rolls back PR #598 into 1.10.1.
=> 1.10: Fix cpc-name handling for cpc autostart add

docs/changes.rst, zhmccli/_cmd_cpc.py
Fixes #605 
- allow for uri/wwpn preserve and adapter mapping via config file
- include meta information in export data, dump/remove during import
- dump configuration after export / prior import
- move user confirmation accordingly
=> Improve dpm-import and dpm-export

.safety-policy-all.yml, dev-requirements.txt, docs/changes.rst, minimum-constraints-install.txt, minimum-constraints.txt, requirements.txt
Rolls back PR #625 into 1.11.1.
=> 1.11: Addressed safety issues up to 2024-07-21

.safety-policy-install.yml, docs/changes.rst, minimum-constraints-install.txt, requirements.txt
Cannot be rolled back to 1.10.x because of the requirement for Python>=3.8.
=> Increased minimum version of zhmcclient to 1.17.0

.github/workflows/test.yml, Makefile, changes/1665.fix.rst
Was reviewed in https://github.com/zhmcclient/python-zhmcclient/pull/1664 - no separate review needed.
=> Fixed coveralls not found on MacOS with py39-311

changes/659.fix.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
=> Increased zhmcclient to 1.18.0

changes/676.fix.rst, zhmccli/_helper.py
=> Fixed AttributeError when ending interactive LPAR console session

changes/676.fix.rst, zhmccli/_helper.py
Rolls back PR #677 into 1.12.1.
=> 1.12: Fixed AttributeError when ending interactive LPAR console session

Makefile, changes/544.2.feature.rst, changes/544.2.incompatible.rst, changes/544.deprecation.rst, changes/544.feature.rst, changes/544.incompatible.rst, minimum-constraints-install.txt, requirements.txt, tests/end2end/test_session.py, tests/end2end/utils.py, tests/function/test_info.py, tests/function/test_session_file.py, tests/function/utils.py, tests/unit/test_helper.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_session.py, zhmccli/_helper.py, zhmccli/_session_file.py, zhmccli/zhmccli.py
For details, see the commit message and the change entries.
The PR is ready for review.
End2end tests with test_session.py have passed on A224.
=> Support for session logon/logoff commands and for named sessions

changes/noissue.safety.fix.rst, minimum-constraints-install.txt, requirements.txt
In the master branch, zhmcclient is already at 1.19.0, so no separate PR needed for this change here.,
=> 1.12: Safety issues up to 2025-01-12

.github/workflows/publish.yml, changes/712.feature.rst
In addition, I have created the environment named "pypi" on this repo.
GitHub had already been added earlier as trusted publisher to the Pypi project.
=> Started using the trusted publisher concept of Pypi

.github/workflows/publish.yml, changes/712.feature.rst
=> 1.12: Started using the trusted publisher concept of Pypi

zhmccli/_cmd_metrics.py, zhmccli/_helper.py
Reason is that the minimum version of Python is not 3.8, and since Python 3.6, the standard dict is ordered.
=> Replaced OrderedDict with standard dict

changes/noissue.safety.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
=> 1.12: Increased safety to 3.4.0 and updated its dependencies; Safety issues

changes/730.feature.1.rst, changes/730.feature.2.rst, tests/unit/test_helper.py, zhmccli/_cmd_console.py, zhmccli/_cmd_cpc.py, zhmccli/_helper.py
The new command groups 'console hw-message' and 'cpc hw-message' have been tested manually with T224.
Note: end2end testcases are not included in this PR and are covered by issue #734.
=> Support for Console and CPC Hardware Messages

changes/739.fix.rst, zhmccli/_cmd_storagegroup.py
Tested manually on T224.
Before:
```
$ zhmc storagegroup show pok-ahps-iep-rhel-01
+------------------------------+--------------------------------------------------------------------+
| Field Name                   | Value                                                              |
|------------------------------+--------------------------------------------------------------------|
| candidate-adapter-port-names | Port 0                                                             |
|                              | Port 0                                                             |
|                              | Port 0                                                             |
|                              | Port 0 …
```
=> Show candidate adapter names in 'storagegroup show'

changes/739.fix.rst, zhmccli/_cmd_storagegroup.py
=> 1.12: Show candidate adapter names in 'storagegroup show'

changes/747.feature.rst, changes/747.fix.rst, zhmccli/_cmd_nic.py, zhmccli/_cmd_port.py, zhmccli/_cmd_storagegroup.py, zhmccli/_cmd_storagevolume.py, zhmccli/_cmd_vstorageresource.py
I tested the change manually with the "storagegroup add/remove-port" commands on the AHPS system.
=> Fixed and enhanced --port option of multiple commands

changes/752.feature.rst, zhmccli/_cmd_adapter.py, zhmccli/_cmd_capacitygroup.py, zhmccli/_cmd_certificates.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_imageprofile.py, zhmccli/_cmd_ldap_server_definition.py, zhmccli/_cmd_loadprofile.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_password_rule.py, zhmccli/_cmd_port.py, zhmccli/_cmd_resetprofile.py, zhmccli/_cmd_storagegroup.py, zhmccli/_cmd_storagevolume.py, zhmccli/_cmd_unmanaged_cpc.py, zhmccli/_cmd_user.py, zhmccli/_cmd_user_pattern.py, zhmccli/_cmd_user_role.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vstorageresource.py, zhmccli/_cmd_vswitch.py, zhmccli/_helper.py
I testes this on AHPS with the following commands:
```
zhmc cpc list --help                                       # test help text
zhmc cpc list --filter                                     # test error handling for missing option arg
zhmc cpc list --filter xxx                                 # test error handling for missing "="
zhmc cpc list                                              # test no filtering
zhmc cpc list --filter name=A224                           # test string property
zhmc cpc list --filter "name='A224'"                       # test string with single quotes
zhmc cpc list --filter 'name="A224"'                       # test string with double quotes
zhmc cpc list --filter "name=A.*"                          # test regular expression …
```
=> Added support for filtering list output by property values

changes/742.feature.rst, zhmccli/_cmd_adapter.py, zhmccli/_cmd_capacitygroup.py, zhmccli/_cmd_certificates.py, zhmccli/_cmd_cpc.py, zhmccli/_cmd_hba.py, zhmccli/_cmd_imageprofile.py, zhmccli/_cmd_ldap_server_definition.py, zhmccli/_cmd_loadprofile.py, zhmccli/_cmd_lpar.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_partition.py, zhmccli/_cmd_password_rule.py, zhmccli/_cmd_port.py, zhmccli/_cmd_resetprofile.py, zhmccli/_cmd_storagegroup.py, zhmccli/_cmd_storagevolume.py, zhmccli/_cmd_unmanaged_cpc.py, zhmccli/_cmd_user.py, zhmccli/_cmd_user_pattern.py, zhmccli/_cmd_user_role.py, zhmccli/_cmd_vfunction.py, zhmccli/_cmd_vstorageresource.py, zhmccli/_cmd_vswitch.py, zhmccli/_helper.py
I tested this on AHPS with the following commands:
```
zhmc cpc list --help                                  # test help text
zhmc cpc list --sort                                  # test error handling for missing option arg
zhmc cpc list --sort xxx                              # test error handling for invalid property name
zhmc cpc list                                         # test default sorting (name)
zhmc cpc list --sort name                             # test excplicit default sort
zhmc cpc list --sort dpm-enabled                      # test boolean property
zhmc cpc list --sort dpm-enabled,name                 # test boolean + string property
zhmc cpc list --sort status                           # test property in table and in list() result …
```
=> Support for sorting output of list commands by properties

changes/731.fix.rst, changes/731.incompatible.rst, tests/end2end/test_cpc.py, tests/function/test_options.py, tests/unit/test_csv.py, zhmccli/_helper.py
This PR also fixes issue #761 because the extended end2end test function `test_cpc_list()` otherwise would need to add rather complex logic to cover all data types and Python versions.
I ran the extended end2end test function `test_cpc_list()` on the HMC of T224:
* All testcases for this test function pass.
* I verified that the new testcases with '--all' surface the prior bug, when using the unfixed code.
=> Fixed null values for list --all; Made CSV quoting consistent

changes/731.fix.rst, zhmccli/_helper.py
Rolls back the `--all` related changes from PR #760 into 1.12.
=> 1.12: Fixed that properties added with --all had null values for json/csv

changes/706.cleanup.rst, changes/706.fix.1.rst, changes/706.fix.2.rst, zhmccli/_cmd_character_rule.py, zhmccli/_cmd_console.py, zhmccli/_cmd_session.py, zhmccli/_cmd_storagegroup.py, zhmccli/_helper.py
I tested this with the HMC of A224:
* full end2end test: `TESTHMC=A224 make end2end`
* manually with all `zhmc ... list*` commands with output formats table, csv, json:
```
zhmc -o $format session list
zhmc -o $format console list-api-features
zhmc -o $format console list-firmware
zhmc -o $format console hw-message list
zhmc -o $format cpc list
zhmc -o $format cpc list-api-features $cpc
zhmc -o $format cpc list-firmware $cpc
zhmc -o $format cpc hw-message list $cpc
zhmc -o $format adapter list $cpc
zhmc -o $format adapter list-nics $cpc $adapter
zhmc -o $format port list $cpc $adapter
zhmc -o $format vswitch list $cpc
zhmc -o $format capacitygroup list $cpc
zhmc -o $format partition list $cpc
zhmc -o $format partition list-storagegroups $cpc $partition …
```
=> Fixed CeasedExistence in 'partition list-storagegroups'; Consolidated prop processing

changes/706.cleanup.rst, changes/706.fix.1.rst, changes/706.fix.2.rst, zhmccli/_cmd_character_rule.py, zhmccli/_cmd_console.py, zhmccli/_cmd_storagegroup.py, zhmccli/_helper.py
Rolls back PR #763 into 1.12.
Tested against the HMC of A224:
* full end2end test: `TESTHMC=A224 make end2end`
* manually with all `zhmc ... list*` commands with output formats table, csv, json:
=> 1.12: Fixed CeasedExistence in 'partition list-storagegroups'; Consolidated prop processing

minimum-constraints-develop.txt
Driven by Mend issue https://github.ibm.com/zhmcclient/zhmccli/issues/38 in the internal repo.
=> Added cryptography as a dev dependency to ensure minimum version

changes/noissue.2.feature.rst, tests/end2end/test_character_rule.py
I verified the new end2end tests on the HMC of A224:
```
TESTHMC=A224 TESTCASES=test_character_rule.py make end2end
```
=> Added end2end testcases for character rules

changes/731.incompatible.rst, docs/cli.rst, tests/end2end/test_character_rule.py, tests/end2end/test_console_hwmessage.py, tests/end2end/test_cpc.py, tests/end2end/test_cpc_hwmessage.py, tests/end2end/utils.py, zhmccli/_helper.py
I tested this on the HMC of AHPS with the complete set of end2end testcases, on Python 3.8, 3.12, and 3.13 (each of which handles CSV quoting slightly differently either when the zhmc command writes the output or when the test functions read the output ):
```
TESTHMC=AHPS make end2end
```
Tests:
=> Consolidated and fixed zhmc output parsing for end2end; Reverted CSV quoting

changes/784.fix.rst, zhmccli/zhmccli.py
=> Fixed that --transpose, --timestats, --pdb were ignored with click 8.2.0

changes/784.fix.rst, zhmccli/zhmccli.py
=> 1.13: Fixed that --transpose, --timestats, --pdb were ignored with click 8.2.0

Makefile, base-requirements.txt, changes/noissue.1.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt, minimum-constraints-install.txt, pyproject.toml
No rollback to 1.13 needed, because that version is still using setup.py.
=> Fixed incorrect package version in build; Increased pipdeptree version

changes/820.feature.rst, changes/820.fix.rst, changes/820.incompatible.rst, tests/end2end/test_nic.py, zhmccli/_cmd_adapter.py, zhmccli/_cmd_nic.py, zhmccli/_cmd_vswitch.py
The PR has been tested:
* Manually with `nic create`, `nic update`, `nic delete`, `vswitch list`, `vswitch show` on OSA NICs on z16 and z17 CPCs
* With the new test_nic.py end2end test cases (which test `nic list`and `nic show`) on z16 and z17 CPCs
=> Fixed issue with creating/updating OSA/HS NICs on z17

changes/noissue.47.fix.rst, dev-requirements.txt
=> 1.13: Circumvented safety issue with import of typer module

Makefile, changes/noissue.2.fix.rst
=> 1.13: Fixed quoting for TESTCASES env var in Makefile

changes/noissue.68.fix.rst, dev-requirements.txt, minimum-constraints-develop.txt
* Typer version was pinned to 0.17.0 due to: pyupio/safety#778
* The issue is fixed with safety 3.6.1, so we no longer need to pin that version.
=> Removed the pinning on typer version <0.17.0 with safety 3.6.1
